# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Workflows commands (::set-output, etc): # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter

name: Test, Build, and Deploy ⚙⚛✨🚀

on:
  push:
    branches: [main, dicoding]

  pull_request:
    branches: [main]

jobs:
  test_build:
    name: Test and Build ⚙⚛

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x, 14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Use NodeJS ${{ matrix.node }} 📦
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea # v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get Yarn Cache Directory Path 🐈
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache Directories 🧶
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2.1.7
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ${{ github.workspace }}/node_modules/.cache
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies ✨
        run: yarn install --immutable --check-cache

      - name: Run Linter 👨🏻‍💻
        run: yarn type-check && yarn lint

      - name: Run Formatter 💅
        run: yarn format

      - name: Run Test 🛠
        run: yarn test

      - name: Run E2E Test 👥🧪
        if: matrix.node-version == '14.x'
        run: yarn test:e2e

      - name: Run Build ⚙
        run: yarn build

      - name: Cache build ready to deploy 🚀
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2.1.7
        with:
          path: |
            ./dist
          key: ${{ github.sha }}-${{ runner.os }}-${{ matrix.node-version }}

  deploy:
    name: Deploy to production ✨🚀
    needs: test_build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dicoding'

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Restore build cache ♻️
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2.1.7
        with:
          path: |
            ./dist
          key: ${{ github.sha }}-${{ runner.os }}-${{ matrix.node-version }}

      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: aladine.latipun.dev

      - name: Deploy 🚀
        if: github.ref == 'refs/heads/dicoding'
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: github-pages-dicoding
